// Code generated by protoc-gen-go.
// source: DiscoverableServiceTransport.proto
// DO NOT EDIT!

/*
Package Transport is a generated protocol buffer package.

It is generated from these files:
	DiscoverableServiceTransport.proto
	Task.proto

It has these top-level messages:
	DiscoverableServiceTransport
	Task
*/
package Transport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type DiscoverableServiceTransport struct {
	Address string `protobuf:"bytes,1,opt,name=Address,json=address" json:"Address,omitempty"`
}

func (m *DiscoverableServiceTransport) Reset()                    { *m = DiscoverableServiceTransport{} }
func (m *DiscoverableServiceTransport) String() string            { return proto.CompactTextString(m) }
func (*DiscoverableServiceTransport) ProtoMessage()               {}
func (*DiscoverableServiceTransport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*DiscoverableServiceTransport)(nil), "Transport.DiscoverableServiceTransport")
}

var fileDescriptor0 = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0x72, 0xc9, 0x2c, 0x4e,
	0xce, 0x2f, 0x4b, 0x2d, 0x4a, 0x4c, 0xca, 0x49, 0x0d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x0d,
	0x29, 0x4a, 0xcc, 0x2b, 0x2e, 0xc8, 0x2f, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x84, 0x0b, 0x28, 0x59, 0x70, 0xc9, 0xe0, 0xd3, 0x20, 0x24, 0xc1, 0xc5, 0xee, 0x98, 0x92, 0x52,
	0x94, 0x5a, 0x5c, 0x2c, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x9e, 0x08, 0xe1, 0x26, 0xb1,
	0x81, 0xcd, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x2c, 0x7d, 0xf1, 0x71, 0x00, 0x00,
	0x00,
}
